In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv("Datasets/link1/anomaly.csv")

In [3]:
df.head()

Col1      Col2      Col3      Col4      Col5      Col6      Col7  \
0  0.263995  0.764929  0.138424  0.935242  0.605867  0.518790  0.912225   
1  0.546092  0.653975  0.065575  0.227772  0.845269  0.837066  0.272379   
2  0.336714  0.538842  0.192801  0.553563  0.074515  0.332993  0.365792   
3  0.092108  0.995017  0.014465  0.176371  0.241530  0.514724  0.562208   
4  0.325261  0.805968  0.957033  0.331665  0.307923  0.355315  0.501899   

       Col8      Col9     Col10  
0  0.608234  0.723782  0.733591  
1  0.331679  0.429297  0.367422  
2  0.861309  0.899017  0.088600  
3  0.158963  0.073715  0.208463  
4  0.558449  0.885169  0.182754

In [4]:
df.corr()

Col1      Col2      Col3      Col4      Col5      Col6      Col7  \
Col1   1.000000 -0.021500 -0.020540 -0.013232  0.005411  0.006928  0.032020   
Col2  -0.021500  1.000000 -0.088408  0.025027 -0.008884 -0.010815  0.028414   
Col3  -0.020540 -0.088408  1.000000 -0.380930  0.035976  0.013407  0.040009   
Col4  -0.013232  0.025027 -0.380930  1.000000  0.008707 -0.001044 -0.011633   
Col5   0.005411 -0.008884  0.035976  0.008707  1.000000  0.799814  0.060070   
Col6   0.006928 -0.010815  0.013407 -0.001044  0.799814  1.000000  0.060688   
Col7   0.032020  0.028414  0.040009 -0.011633  0.060070  0.060688  1.000000   
Col8  -0.009075 -0.038997  0.049876 -0.025769  0.029146  0.047583  0.599083   
Col9   0.022250  0.014015  0.007048  0.021624  0.050786  0.011199  0.794212   
Col10 -0.025724 -0.027462  0.014269  0.021620 -0.028670 -0.034188 -0.482528   

           Col8      Col9     Col10  
Col1  -0.009075  0.022250 -0.025724  
Col2  -0.038997  0.014015 -0.027462  
Col3   0.049876  0.007048  0.014269  
Col4  -0.025769  0.021624  0.021620  
Col5   0.029146  0.050786 -0.028670  
Col6   0.047583  0.011199 -0.034188  
Col7   0.599083  0.794212 -0.482528  
Col8   1.000000  0.366446  0.088228  
Col9   0.366446  1.000000 -0.690842  
Col10  0.088228 -0.690842  1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Col1    1000 non-null   float64
 1   Col2    1000 non-null   float64
 2   Col3    1000 non-null   float64
 3   Col4    1000 non-null   float64
 4   Col5    1000 non-null   float64
 5   Col6    1000 non-null   float64
 6   Col7    1000 non-null   float64
 7   Col8    1000 non-null   float64
 8   Col9    1000 non-null   float64
 9   Col10   1000 non-null   float64
dtypes: float64(10)
memory usage: 78.2 KB


In [6]:
df.isnull().sum()

Col1     0
Col2     0
Col3     0
Col4     0
Col5     0
Col6     0
Col7     0
Col8     0
Col9     0
Col10    0
dtype: int64

In [7]:
df

Col1      Col2      Col3      Col4      Col5      Col6      Col7  \
0    0.263995  0.764929  0.138424  0.935242  0.605867  0.518790  0.912225   
1    0.546092  0.653975  0.065575  0.227772  0.845269  0.837066  0.272379   
2    0.336714  0.538842  0.192801  0.553563  0.074515  0.332993  0.365792   
3    0.092108  0.995017  0.014465  0.176371  0.241530  0.514724  0.562208   
4    0.325261  0.805968  0.957033  0.331665  0.307923  0.355315  0.501899   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.305055  0.656837  0.331665  0.822525  0.907127  0.882276  0.855732   
996  0.812627  0.864258  0.616604  0.167966  0.811223  0.938071  0.418462   
997  0.250967  0.138627  0.919703  0.461234  0.886555  0.869888  0.800908   
998  0.502436  0.936820  0.580062  0.540773  0.151995  0.059452  0.225220   
999  0.457991  0.017755  0.714113  0.125992  0.063316  0.154739  0.922974   

         Col8      Col9     Col10  
0    0.608234  0.723782  0.733591  
1    0.331679  0.429297  0.367422  
2    0.861309  0.899017  0.088600  
3    0.158963  0.073715  0.208463  
4    0.558449  0.885169  0.182754  
..        ...       ...       ...  
995  0.584786  0.808640  0.242762  
996  0.472306  0.348347  0.671129  
997  0.530324  0.779433  0.234952  
998  0.242755  0.279385  0.538755  
999  0.692299  0.816777  0.307592  

[1000 rows x 10 columns]

In [8]:
q1 = df.quantile(0.25)
q3 = df.quantile(0.75)
iqr = q3 - q1
lb = q1 - (1.5*iqr)
ub = q3 + (1.5*iqr)
print(lb,ub)

Col1    -0.322643
Col2    -0.301173
Col3    -0.185867
Col4    -0.457555
Col5    -0.847733
Col6    -0.928302
Col7    -0.592349
Col8    -0.326288
Col9    -0.356881
Col10   -0.164530
dtype: float64 Col1     1.304293
Col2     1.279153
Col3     1.210582
Col4     1.445651
Col5     1.865369
Col6     1.927401
Col7     1.643305
Col8     1.198583
Col9     1.372007
Col10    1.153963
dtype: float64


In [9]:
df = df[(df>lb) & (df<ub)]
df

Col1      Col2      Col3      Col4      Col5      Col6      Col7  \
0    0.263995  0.764929  0.138424  0.935242  0.605867  0.518790  0.912225   
1    0.546092  0.653975  0.065575  0.227772  0.845269  0.837066  0.272379   
2    0.336714  0.538842  0.192801  0.553563  0.074515  0.332993  0.365792   
3    0.092108  0.995017  0.014465  0.176371  0.241530  0.514724  0.562208   
4    0.325261  0.805968  0.957033  0.331665  0.307923  0.355315  0.501899   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.305055  0.656837  0.331665  0.822525  0.907127  0.882276  0.855732   
996  0.812627  0.864258  0.616604  0.167966  0.811223  0.938071  0.418462   
997  0.250967  0.138627  0.919703  0.461234  0.886555  0.869888  0.800908   
998  0.502436  0.936820  0.580062  0.540773  0.151995  0.059452  0.225220   
999  0.457991  0.017755  0.714113  0.125992  0.063316  0.154739  0.922974   

         Col8      Col9     Col10  
0    0.608234  0.723782  0.733591  
1    0.331679  0.429297  0.367422  
2    0.861309  0.899017  0.088600  
3    0.158963  0.073715  0.208463  
4    0.558449  0.885169  0.182754  
..        ...       ...       ...  
995  0.584786  0.808640  0.242762  
996  0.472306  0.348347  0.671129  
997  0.530324  0.779433  0.234952  
998  0.242755  0.279385  0.538755  
999  0.692299  0.816777  0.307592  

[1000 rows x 10 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Col1    1000 non-null   float64
 1   Col2    1000 non-null   float64
 2   Col3    1000 non-null   float64
 3   Col4    1000 non-null   float64
 4   Col5    1000 non-null   float64
 5   Col6    1000 non-null   float64
 6   Col7    1000 non-null   float64
 7   Col8    1000 non-null   float64
 8   Col9    1000 non-null   float64
 9   Col10   1000 non-null   float64
dtypes: float64(10)
memory usage: 78.2 KB


In [12]:
df.describe()

Col1         Col2         Col3         Col4         Col5  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.491362     0.490200     0.509077     0.497362     0.586120   
std       0.259138     0.251931     0.256606     0.263562     0.334658   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.287458     0.291449     0.337802     0.256147     0.169680   
50%       0.492070     0.488656     0.510077     0.497537     0.782019   
75%       0.694192     0.686531     0.686914     0.731949     0.847956   
max       0.994431     1.000000     1.000000     1.000000     1.000000   

              Col6         Col7         Col8         Col9        Col10  
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000  
mean      0.514636     0.508270     0.457541     0.477685     0.495760  
std       0.317470     0.278483     0.220129     0.241432     0.211677  
min       0.000000     0.000000     0.000000     0.000000     0.014495  
25%       0.142587     0.246021     0.245539     0.291452     0.329904  
50%       0.537953     0.465679     0.515619     0.387753     0.488891  
75%       0.856512     0.804935     0.626757     0.723674     0.659528  
max       1.000000     1.000000     1.000000     0.988732     1.000000

In [13]:
df.isnull().sum()

Col1     0
Col2     0
Col3     0
Col4     0
Col5     0
Col6     0
Col7     0
Col8     0
Col9     0
Col10    0
dtype: int64

In [14]:
X = df.iloc[:,:-1]
X.head()

Col1      Col2      Col3      Col4      Col5      Col6      Col7  \
0  0.263995  0.764929  0.138424  0.935242  0.605867  0.518790  0.912225   
1  0.546092  0.653975  0.065575  0.227772  0.845269  0.837066  0.272379   
2  0.336714  0.538842  0.192801  0.553563  0.074515  0.332993  0.365792   
3  0.092108  0.995017  0.014465  0.176371  0.241530  0.514724  0.562208   
4  0.325261  0.805968  0.957033  0.331665  0.307923  0.355315  0.501899   

       Col8      Col9  
0  0.608234  0.723782  
1  0.331679  0.429297  
2  0.861309  0.899017  
3  0.158963  0.073715  
4  0.558449  0.885169

In [16]:
y = df.iloc[:,-1].values
y

array([0.73359095, 0.367422  , 0.08860015, 0.20846322, 0.18275441,
       0.73667236, 0.5385133 , 0.04984305, 0.8915485 , 0.30886422,
       0.44142657, 0.02872877, 0.89402301, 0.93107397, 0.30569249,
       0.44278137, 0.57151805, 0.29276917, 0.26576145, 0.16202786,
       0.98271077, 0.31398743, 0.67400835, 0.97336982, 0.85723909,
       0.84739121, 0.08061096, 0.62034258, 0.84478848, 0.41001696,
       0.3775165 , 0.49993252, 0.95914448, 0.78092936, 0.80819045,
       0.48440096, 0.288307  , 0.44263045, 0.35861547, 0.66951293,
       0.40329547, 0.68418966, 0.80636851, 0.8420881 , 0.56456355,
       0.16077867, 0.44268874, 0.96937017, 0.16079203, 0.48870593,
       0.48508018, 0.3012969 , 0.94116575, 0.40299127, 0.64113269,
       0.16872365, 0.49891798, 0.63208103, 0.59353976, 0.40650454,
       0.84294363, 0.42295679, 0.74436193, 0.9546502 , 0.27053245,
       0.27767003, 0.90568819, 0.74242736, 0.21486164, 0.78738793,
       0.71005048, 0.56003382, 0.39919244, 0.53365671, 0.28359

In [17]:
y.reshape(-1,1)

array([[0.73359095],
       [0.367422  ],
       [0.08860015],
       [0.20846322],
       [0.18275441],
       [0.73667236],
       [0.5385133 ],
       [0.04984305],
       [0.8915485 ],
       [0.30886422],
       [0.44142657],
       [0.02872877],
       [0.89402301],
       [0.93107397],
       [0.30569249],
       [0.44278137],
       [0.57151805],
       [0.29276917],
       [0.26576145],
       [0.16202786],
       [0.98271077],
       [0.31398743],
       [0.67400835],
       [0.97336982],
       [0.85723909],
       [0.84739121],
       [0.08061096],
       [0.62034258],
       [0.84478848],
       [0.41001696],
       [0.3775165 ],
       [0.49993252],
       [0.95914448],
       [0.78092936],
       [0.80819045],
       [0.48440096],
       [0.288307  ],
       [0.44263045],
       [0.35861547],
       [0.66951293],
       [0.40329547],
       [0.68418966],
       [0.80636851],
       [0.8420881 ],
       [0.56456355],
       [0.16077867],
       [0.44268874],
       [0.969

In [18]:
X.head()

Col1      Col2      Col3      Col4      Col5      Col6      Col7  \
0  0.263995  0.764929  0.138424  0.935242  0.605867  0.518790  0.912225   
1  0.546092  0.653975  0.065575  0.227772  0.845269  0.837066  0.272379   
2  0.336714  0.538842  0.192801  0.553563  0.074515  0.332993  0.365792   
3  0.092108  0.995017  0.014465  0.176371  0.241530  0.514724  0.562208   
4  0.325261  0.805968  0.957033  0.331665  0.307923  0.355315  0.501899   

       Col8      Col9  
0  0.608234  0.723782  
1  0.331679  0.429297  
2  0.861309  0.899017  
3  0.158963  0.073715  
4  0.558449  0.885169

Splitting

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)
X_train.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
Col5    0
Col6    0
Col7    0
Col8    0
Col9    0
dtype: int64

In [20]:
from sklearn.preprocessing import StandardScaler
ss_x = StandardScaler()
ss_y = StandardScaler()

## Linear Regression

In [21]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [22]:
import matplotlib.pyplot as plt

In [23]:
reg.predict(X).reshape(-1,1)

array([[0.35845833],
       [0.4740324 ],
       [0.45599676],
       [0.53706664],
       [0.31804515],
       [0.24557225],
       [0.64739336],
       [0.41797166],
       [0.61039497],
       [0.20385241],
       [0.66070553],
       [0.21401793],
       [0.58334516],
       [0.69551415],
       [0.59306424],
       [0.82950479],
       [0.54078078],
       [0.8899369 ],
       [0.47562039],
       [0.35853509],
       [0.06489891],
       [0.52048553],
       [0.34579008],
       [0.4937047 ],
       [0.36069237],
       [0.09045878],
       [0.29197311],
       [0.80598781],
       [0.55753297],
       [0.90892112],
       [0.75535963],
       [0.6018645 ],
       [0.32026587],
       [0.45481484],
       [0.95007614],
       [0.16652071],
       [0.65283957],
       [0.77519046],
       [0.34990947],
       [0.45971144],
       [0.39600338],
       [0.48025585],
       [0.51793512],
       [0.49987356],
       [0.29378808],
       [0.86125461],
       [0.28083946],
       [0.520

In [26]:
reg.coef_

array([-1.50010659e-04,  1.22417389e-02,  3.57404359e-02,  4.68036749e-02,
        4.13594305e-02, -6.09848928e-02, -1.94250721e-01,  4.89167370e-01,
       -5.88113000e-01])

In [28]:
reg.score(X_test,y_test)

0.601517745353966

## Polynomial Regression

In [33]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree =2)
X_poly = poly.fit_transform(X_train)
X_poly_test = poly.fit_transform(X_test)
polyreg = LinearRegression()
polyreg.fit(X_poly,y_train)

LinearRegression()

In [34]:
polyreg.score(X_poly_test,y_test)

0.5679486383662451

In [36]:
poly3 = PolynomialFeatures(degree =3)
X_poly3 = poly3.fit_transform(X_train)
X_test_poly3 = poly3.fit_transform(X_test)

polyreg3 = LinearRegression()
polyreg3.fit(X_poly3,y_train)

LinearRegression()

In [37]:
polyreg3.score(X_test_poly3,y_test)

-0.3672045751771551

## Support Vector Machines

In [39]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(X_train,y_train)

SVR()

In [40]:
svr.score(X_test,y_test)

0.6689680846326345

## Decision Tree Regressor

In [41]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state = 0)
dtr.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

In [42]:
dtr.score(X_test,y_test)

0.41597535958906373

## Lasso-Ridge Regressor

In [43]:
from sklearn.linear_model import Ridge
ridgeR = Ridge(alpha = 3)
ridgeR.fit(X_train,y_train)

Ridge(alpha=3)

In [44]:
ridgeR.score(X_test,y_test)

0.602270165565817