In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv("Datasets/link1/bank.csv")

In [3]:
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome deposit  
0  unknown    5   may       261         1     -1         0  unknown      no  
1  unknown    5   may       151         1     -1         0  unknown      no  
2  unknown    5   may        76         1     -1         0  unknown      no  
3  unknown    5   may        92         1     -1         0  unknown      no  
4  unknown    5   may       198         1     -1         0  unknown      no

In [4]:
df

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome  \
0        unknown    5   may       261         1     -1         0  unknown   
1        unknown    5   may       151         1     -1         0  unknown   
2        unknown    5   may        76         1     -1         0  unknown   
3        unknown    5   may        92         1     -1         0  unknown   
4        unknown    5   may       198         1     -1         0  unknown   
...          ...  ...   ...       ...       ...    ...       ...      ...   
45206   cellular   17   nov       977         3     -1         0  unknown   
45207   cellular   17   nov       456         2     -1         0  unknown   
45208   cellular   17   nov      1127         5    184         3  success   
45209  telephone   17   nov       508         4     -1         0  unknown   
45210   cellular   17   nov       361         2    188        11    other   

      deposit  
0          no  
1          no  
2          no  
3          no  
4          no  
...       ...  
45206     yes  
45207     yes  
45208     yes  
45209      no  
45210      no  

[45211 rows x 17 columns]

In [5]:
df.marital.value_counts()

married     27214
single      12790
divorced     5207
Name: marital, dtype: int64

In [6]:
df.job.value_counts()

blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: job, dtype: int64

In [7]:
df.education.value_counts()

secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: education, dtype: int64

In [8]:
df.default.value_counts()

no     44396
yes      815
Name: default, dtype: int64

In [9]:
df.contact.value_counts()

cellular     29285
unknown      13020
telephone     2906
Name: contact, dtype: int64

In [10]:
df.month.value_counts()

may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: month, dtype: int64

In [11]:
df.poutcome.value_counts()

unknown    36959
failure     4901
other       1840
success     1511
Name: poutcome, dtype: int64

In [12]:
y = df.balance.values
y

array([2143,   29,    2, ..., 5715,  668, 2971], dtype=int64)

In [13]:
y = y.reshape(-1,1)
y

array([[2143],
       [  29],
       [   2],
       ...,
       [5715],
       [ 668],
       [2971]], dtype=int64)

In [14]:
X = df.drop(['balance'],axis = 1)
X

age           job   marital  education default housing loan    contact  \
0       58    management   married   tertiary      no     yes   no    unknown   
1       44    technician    single  secondary      no     yes   no    unknown   
2       33  entrepreneur   married  secondary      no     yes  yes    unknown   
3       47   blue-collar   married    unknown      no     yes   no    unknown   
4       33       unknown    single    unknown      no      no   no    unknown   
...    ...           ...       ...        ...     ...     ...  ...        ...   
45206   51    technician   married   tertiary      no      no   no   cellular   
45207   71       retired  divorced    primary      no      no   no   cellular   
45208   72       retired   married  secondary      no      no   no   cellular   
45209   57   blue-collar   married  secondary      no      no   no  telephone   
45210   37  entrepreneur   married  secondary      no      no   no   cellular   

       day month  duration  campaign  pdays  previous poutcome deposit  
0        5   may       261         1     -1         0  unknown      no  
1        5   may       151         1     -1         0  unknown      no  
2        5   may        76         1     -1         0  unknown      no  
3        5   may        92         1     -1         0  unknown      no  
4        5   may       198         1     -1         0  unknown      no  
...    ...   ...       ...       ...    ...       ...      ...     ...  
45206   17   nov       977         3     -1         0  unknown     yes  
45207   17   nov       456         2     -1         0  unknown     yes  
45208   17   nov      1127         5    184         3  success     yes  
45209   17   nov       508         4     -1         0  unknown      no  
45210   17   nov       361         2    188        11    other      no  

[45211 rows x 16 columns]

In [15]:
X.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [16]:
dumcateg = ['job','marital','education','contact','month','poutcome']
for feat in dumcateg:
    dummy = pd.get_dummies(X[feat],drop_first=True)
    X = X.drop([feat],axis = 1)
    X = pd.concat([X,dummy],axis =1 )
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [17]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 42 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            45211 non-null  int64 
 1   default        45211 non-null  object
 2   housing        45211 non-null  object
 3   loan           45211 non-null  object
 4   day            45211 non-null  int64 
 5   duration       45211 non-null  int64 
 6   campaign       45211 non-null  int64 
 7   pdays          45211 non-null  int64 
 8   previous       45211 non-null  int64 
 9   deposit        45211 non-null  object
 10  blue-collar    45211 non-null  uint8 
 11  entrepreneur   45211 non-null  uint8 
 12  housemaid      45211 non-null  uint8 
 13  management     45211 non-null  uint8 
 14  retired        45211 non-null  uint8 
 15  self-employed  45211 non-null  uint8 
 16  services       45211 non-null  uint8 
 17  student        45211 non-null  uint8 
 18  technician     45211 non-n

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
categle = ['default','housing','loan','deposit']
for feat in categle:
    X[feat] = le.fit_transform(X[feat])
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 42 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            45211 non-null  int64
 1   default        45211 non-null  int32
 2   housing        45211 non-null  int32
 3   loan           45211 non-null  int32
 4   day            45211 non-null  int64
 5   duration       45211 non-null  int64
 6   campaign       45211 non-null  int64
 7   pdays          45211 non-null  int64
 8   previous       45211 non-null  int64
 9   deposit        45211 non-null  int32
 10  blue-collar    45211 non-null  uint8
 11  entrepreneur   45211 non-null  uint8
 12  housemaid      45211 non-null  uint8
 13  management     45211 non-null  uint8
 14  retired        45211 non-null  uint8
 15  self-employed  45211 non-null  uint8
 16  services       45211 non-null  uint8
 17  student        45211 non-null  uint8
 18  technician     45211 non-null  uint8
 19  unem

Splitting

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [20]:
from sklearn.preprocessing import StandardScaler
ss_x = StandardScaler()
ss_y = StandardScaler()

## Linear Regression

In [21]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(ss_x.fit_transform(X),ss_y.fit_transform(y))

LinearRegression()

In [22]:
import matplotlib.pyplot as plt

In [23]:
ss_y.inverse_transform(reg.predict(ss_x.transform(X_test)))

array([[ 597.49567436],
       [1412.03591709],
       [1137.57459079],
       ...,
       [1249.80176502],
       [ 936.01355404],
       [2513.06496128]])

In [24]:
reg.score(ss_x.transform(X_test),ss_y.transform(y_test))

0.05108450980057344

## Polynomial Regression

In [27]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree =2)
X_polytrain = poly.fit_transform(ss_x.transform(X_train))
X_polytest = poly.fit_transform(ss_x.transform(X_test))

polyreg = LinearRegression()
polyreg.fit(X_polytrain,y)

ValueError: Found input variables with inconsistent numbers of samples: [36168, 45211]

In [ ]:
X.shape

In [ ]:
sns.lineplot(x=X['month_parsed'].dt.year,y=pd.DataFrame(y,columns=['sales']).sales)
sns.lineplot(x=X['month_parsed'].dt.year,y=pd.DataFrame(polyreg.predict(X_poly).reshape(-1,1),columns=['sales']).sales)

## Support Vector Machines

In [ ]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(X,y)

In [ ]:
svr.predict(X)

In [ ]:
sns.lineplot(x=X['month_parsed'].dt.year,y=pd.DataFrame(y,columns=['sales']).sales)
sns.lineplot(x=X['month_parsed'].dt.year,y=pd.DataFrame(svr.predict(X).reshape(-1,1),columns=['sales']).sales)

## Decision Tree Regressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state = 0)
dtr.fit(X,y)

In [ ]:
sns.lineplot(x=X['month_parsed'].dt.year,y=pd.DataFrame(y,columns=['sales']).sales)
sns.lineplot(x=X['month_parsed'].dt.year,y=pd.DataFrame(dtr.predict(X).reshape(-1,1),columns=['sales']).sales)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)
X_train.isnull().sum()

In [ ]:
X_train.columns = X_train.columns.astype(str)
X_test.columns = X_test.columns.astype(str)

In [ ]:
df.head()

In [ ]:
dtr1 = DecisionTreeRegressor(random_state = 0)
dtr1.fit(X_train,y_train.reshape(-1,1))

In [ ]:
X_test

In [ ]:
y

In [ ]:
plt.scatter(X_test,pd.DataFrame(y_test,columns=['sales']).sales)
plt.plot(X_test,pd.DataFrame(dtr1.predict(X_test).reshape(-1,1),columns=['sales']).sales)

## Lasso-Ridge Regressor

In [ ]:
from sklearn.linear_model import Ridge
ridgeR = Ridge(alpha = 3)
ridgeR.fit(X1_ohe,y)

In [ ]:
sns.lineplot(x=X['month_parsed'].dt.year,y=pd.DataFrame(y,columns=['sales']).sales)
sns.lineplot(x=X['month_parsed'].dt.year,y=pd.DataFrame(ridgeR.predict(X1_ohe).reshape(-1,1),columns=['sales']).sales)